config/routes.rb
SearchApplication::Application.routes.draw do

  resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :contacts
    resources :territories
    root  'static_pages#home'
    match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
    match '/help',    to: 'static_pages#help',    via: 'get'
    match '/about',   to: 'static_pages#about',   via: 'get'
    
    

end

app/models/territory.rb
class Territory < ActiveRecord::Base
  has_one :user
end

app/controllers/territories_controller.rb
class TerritoriesController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  before_action :set_territory, only: [:show, :edit, :update, :destroy]
  def create
    @territory = Territory.new(territory_params)
    if @territory.save
      redirect_to @territory
    end
  end
  def new
    @territory = Territory.new
  end

  # GET /territories/1/edit
  def edit
  end

  # POST /territories
  # POST /territories.json
  def create
    @territory = Territory.new(territory_params)

    respond_to do |format|
      if @territory.save
        format.html { redirect_to @territory, notice: 'Territory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @territory }
      else
        format.html { render action: 'new' }
        format.json { render json: @territory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /territories/1
  # PATCH/PUT /territories/1.json
  def update
    respond_to do |format|
      if @territory.update(territory_params)
        format.html { redirect_to @territory, notice: 'Territory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @territory.errors, status: :unprocessable_entity }
      end
    end
  end
  def index
      @territories = Territory.all
    end
  def show
      @territory = Territory.find(params[:id])
    end
    def destroy
      @territory.destroy
      respond_to do |format|
        format.html { redirect_to territories_url }
        format.json { head :no_content }
      end
    end
  private
  def territory_params
    params.require(:territory).permit(:description, :city, :coordinates,
                                 :publisher_id)
  end
  def set_territory
    @territory = Territory.find(params[:id])
  end
end

app/views/territories/_form.html.erb
<%= form_for(@territory) do |f| %>
  <% if @territory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@territory.errors.count, "error") %> prohibited this territory from being saved:</h2>

      <ul>
      <% @territory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :coordinates %><br>
    <%= f.text_area :coordinates %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/territories/_territory.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/territories/edit.html.erb
<h1>Editing territory</h1>

<%= render 'form' %>

<%= link_to 'Show', @territory %> |
<%= link_to 'Back', territories_path %>

app/views/territories/index.html.erb
<h1>Listing Territories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @territories.each do |territory| %>
      <tr>
        <td><%= territory.id %></td>
        <td><%= territory.city %></td>
        <td><%= link_to 'Show', territory %></td>
        <td><%= link_to 'Edit', edit_territory_path(territory) %></td>
        <td><%= link_to 'Destroy', territory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Territory', new_territory_path %>

app/views/territories/new.html.erb
<h1>New Territory</h1>

<%= render 'form' %>

<%= link_to 'Back', territories_path %>

app/views/territories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @territory.city %>
</p>

<p>
  <strong>Description:</strong>
  <%= @territory.description %>
</p>

<%= link_to 'Edit', edit_territory_path(@territory) %> |
<%= link_to 'Back', territories_path %>